# Setup
title: FOOTPRINTS OF MY CHALLENGE🍎
tagline: "Computer Universe"
description: "Daehoon, Seong who is passionate for this domain."
url: http://seongdaehoon.github.com
baseurl: ""
paginate: 5
permalink: pretty

# About/contact
author:
  name: Daehoon Seong
  url: https://twitter.com/danny_seong
  email: daehoon.seong@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y
